CREATE  TABLE IF NOT EXISTS `TABELA_ENTIDADE_ONE_TO_MANY` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(60) NOT NULL,
  `NOME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`)
)ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS `TABELA_ENTIDADE_ONE_TO_MANY_ORM` (
  `ID_ENTIDADE_ONE_TO_MANY` BIGINT(20) NOT NULL,
  `ID_ORM` BIGINT(20) NOT NULL,
  INDEX `FK_ENTIDADE_ONE_TO_MANY_ORM_ENTIDADE_ONE_TO_MANY_ORM` (`ID_ENTIDADE_ONE_TO_MANY` ASC),
  INDEX `FK_ENTIDADE_ONE_TO_MANY_ORM_ORM` (`ID_ORM` ASC),
  CONSTRAINT `FK_ENTIDADE_ONE_TO_MANY_ORM_ENTIDADE_ONE_TO_MANY_ORM`
    FOREIGN KEY (`ID_ENTIDADE_ONE_TO_MANY`)
    REFERENCES `TABELA_ENTIDADE_ONE_TO_MANY`(`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ENTIDADE_ONE_TO_MANY_ORM_ORM`
    FOREIGN KEY (`ID_ORM`)
    REFERENCES `TABELA_ORM`(`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;