CREATE  TABLE IF NOT EXISTS `TABELA_ORM` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `COLUMN_STRING` VARCHAR(60) NULL,
  `COLUMN_INTEGER` INT(10) NULL,
  `COLUMN_BIGDECIMAL` DECIMAL(10, 4) NULL,
  `COLUMN_CALENDAR` DATETIME NULL,
  PRIMARY KEY (`ID`)
)ENGINE = InnoDB;