CREATE  TABLE IF NOT EXISTS `TABELA_USUARIO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(60) NULL,
  `EMAIL` VARCHAR(60) NULL,
  PRIMARY KEY (`ID`)
)ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS `TABELA_AMIGOS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DATA_SOLICITACAO` DATETIME NULL,
  `ID_USUARIO_SOLICITANTE` BIGINT(20) NOT NULL,
  `ID_USUARIO_SOLICITADO` BIGINT(20) NOT NULL,
  `DATA_CONFIRMACAO` DATETIME NULL,
  `SITUACAO` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_USUARIO_SOLICITANTE` (`ID_USUARIO_SOLICITANTE` ASC),
  INDEX `FK_USUARIO_SOLICITADO` (`ID_USUARIO_SOLICITADO` ASC),
  CONSTRAINT `FK_USUARIO_SOLICITANTE`
    FOREIGN KEY (`ID_USUARIO_SOLICITANTE`)
    REFERENCES `TABELA_USUARIO`(`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USUARIO_SOLICITADO`
    FOREIGN KEY (`ID_USUARIO_SOLICITADO`)
    REFERENCES `TABELA_USUARIO`(`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;