CREATE  TABLE IF NOT EXISTS `TABELA_ENTIDADE_ONE_TO_ONE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(60) NOT NULL,
  `NOME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`)
)ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS `TABELA_ENTIDADE_ONE_TO_ONE_ORM` (
  `ID_ENTIDADE_ONE_TO_ONE` BIGINT(20) NOT NULL,
  `ID_ORM` BIGINT(20) NOT NULL,
  INDEX `FK_ENTIDADE_ONE_TO_ONE_ORM_ENTIDADE_ONE_TO_ONE_ORM` (`ID_ENTIDADE_ONE_TO_ONE` ASC),
  INDEX `FK_ENTIDADE_ONE_TO_ONE_ORM_ORM` (`ID_ORM` ASC),
  CONSTRAINT `FK_ENTIDADE_ONE_TO_ONE_ORM_ENTIDADE_ONE_TO_ONE_ORM`
    FOREIGN KEY (`ID_ENTIDADE_ONE_TO_ONE`)
    REFERENCES `TABELA_ENTIDADE_ONE_TO_ONE`(`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ENTIDADE_ONE_TO_ONE_ORM_ORM`
    FOREIGN KEY (`ID_ORM`)
    REFERENCES `TABELA_ORM`(`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;